import NavBar from "@/components/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      {/* <GA GA_MEASUREMENT_ID='G-52GQ441X7H' /> */}
      <body className={inter.className}>
        <NavBar />
        <Toaster />
        <div>{children}</div>
      </body>
    </html>
  );
}
